#!/bin/sh
touch /etc/config/mesh_node

uci -q batch <<-EOF
	set mesh_node.main=mesh_node
	set mesh_node.main.enabled='0'
	commit mesh_node
EOF

chmod +x /etc/init.d/mesh_node
/etc/init.d/mesh_node enable   2>/dev/null || true
/etc/init.d/mesh_node restart  2>/dev/null || true

/etc/init.d/usteer stop      2>/dev/null || true
/etc/init.d/usteer disable   2>/dev/null || true
/etc/init.d/mesh11sd stop    2>/dev/null || true
/etc/init.d/mesh11sd disable 2>/dev/null || true

rm -f /tmp/luci-*
exit 0
