#!/bin/sh

echo -e "config mesh_node 'main'\nconfig mesh_node 'globals'" > /etc/config/mesh_node
chmod +x /etc/init.d/mesh_node
/etc/init.d/mesh11sd stop    2>/dev/null || true
/etc/init.d/mesh11sd disable 2>/dev/null || true
rm -f /tmp/luci-*
exit 0
