#!/bin/sh
mkdir -p /etc/nikki/profiles \
         /etc/nikki/subscriptions \
         /etc/nikki/run/providers/rule \
         /etc/nikki/run/providers/proxy

chmod +x /etc/init.d/nikki \
         /etc/nikki/scripts/debug.sh \
         /etc/nikki/scripts/include.sh \
         /etc/nikki/scripts/firewall_include.sh

rm -f /tmp/luci-*
exit 0
