#!/bin/sh

chmod +x /etc/init.d/nikki
chmod +x /etc/nikki/scripts/*
. /lib/functions.sh
. /etc/nikki/scripts/include.sh

mkdir -p "$SUBSCRIPTIONS_DIR" "$RULE_PROVIDERS_DIR" "$PROXY_PROVIDERS_DIR" /etc/nikki/certs
[ -x /usr/bin/mihomo ] && ln -sf /usr/bin/mihomo "$PROG"

config_load nikki

migrate_rac_cgroup_item() {
	local cgroup="$1" cfg="$2"
	[ -d "/sys/fs/cgroup/$cgroup" ] && return
	uci -q del_list "nikki.$cfg.cgroup=$cgroup"
}

migrate_router_access_control_cgroup() {
	local cfg="$1" dns proxy
	config_get_bool dns   "$cfg" dns
	config_get_bool proxy "$cfg" proxy
	[ "$dns" = 0 ] && uci -q set "nikki.$cfg.dns=$proxy"
	config_list_foreach "$cfg" cgroup migrate_rac_cgroup_item "$cfg"
}

config_foreach migrate_router_access_control_cgroup router_access_control

config_get init config init
[ -n "$init" ] && {
	random=$(awk 'BEGIN{srand(); printf "%06d", int(rand() * 1000000)}')
	uci -q del nikki.config.init
	uci -q set nikki.mixin.api_secret="$random"
	uci -q set nikki.@authentication[0].password="$random"
}

raw="$(uname -m 2>/dev/null)"
[ -n "$raw" ] || raw="$(apk --print-arch 2>/dev/null)"
[ -n "$raw" ] || raw="$(opkg status libc 2>/dev/null | awk -F': ' '/^Architecture/{print $2; exit}')"

case "$raw" in
	x86_64|amd64)          arch="amd64-compatible" ;;
	aarch64*|arm64)        arch="arm64" ;;
	armv7*|arm_cortex-a[7-9]*|arm_cortex-a1[0-9]*) arch="armv7" ;;
	armv6*|arm_cortex-a[56]*) arch="armv6" ;;
	arm*)                  arch="armv5" ;;
	i[3-6]86)              arch="386" ;;
	mips64el*)             arch="mips64le" ;;
	mips64*)               arch="mips64" ;;
	mipsel*)               arch="mipsle" ;;
	mips*)                 arch="mips" ;;
	*)                     arch="amd64" ;;
esac
uci -q set nikki.config.core_version="$arch"

uci -q batch <<-EOF > /dev/null
	del firewall.nikki
	set firewall.nikki=include
	set firewall.nikki.type=script
	set firewall.nikki.fw4_compatible=1
	set firewall.nikki.path=$FIREWALL_INCLUDE_SH
	commit nikki
	commit firewall
EOF

rm -f /tmp/luci-*

exit 0
