#!/bin/sh

chmod +x /etc/init.d/nikki \
         /etc/nikki/scripts/debug.sh \
         /etc/nikki/scripts/include.sh \
         /etc/nikki/scripts/firewall_include.sh

. /lib/functions.sh
. /etc/nikki/scripts/include.sh
mkdir -p "$SUBSCRIPTIONS_DIR" "$RULE_PROVIDERS_DIR" "$PROXY_PROVIDERS_DIR" /etc/nikki/certs
[ -x /usr/bin/mihomo ] && ln -sf /usr/bin/mihomo "$PROG"

config_load nikki

migrate_rac_cgroup_item() {
	local cgroup="$1" cfg="$2"
	[ -d "/sys/fs/cgroup/$cgroup" ] && return
	uci -q del_list "nikki.$cfg.cgroup=$cgroup"
}

migrate_router_access_control_cgroup() {
	local cfg="$1" dns proxy
	config_get_bool dns   "$cfg" dns
	config_get_bool proxy "$cfg" proxy
	[ "$dns" = 0 ] && uci -q set "nikki.$cfg.dns=$proxy"
	config_list_foreach "$cfg" cgroup migrate_rac_cgroup_item "$cfg"
}

config_foreach migrate_router_access_control_cgroup router_access_control

config_get init config init
[ -n "$init" ] && {
	random=$(awk 'BEGIN{srand(); printf "%06d", int(rand() * 1000000)}')
	uci -q del nikki.config.init
	uci -q set nikki.mixin.api_secret="$random"
	uci -q set nikki.@authentication[0].password="$random"
}

source "/etc/openwrt_release"
case "${DISTRIB_ARCH}" in
    aarch64_*)
        core_arch="linux-arm64"
        ;;
    arm_*_neon*|arm_*_vfpv3*|arm_*_vfpv4*|arm_*_neon-vfpv4*)
        core_arch="linux-armv7"
        ;;
    arm_*_vfp*)
        core_arch="linux-armv6"
        ;;
    arm*)
        core_arch="linux-armv5"
        ;;
    i386_*|i686_*)
        core_arch="linux-386"
        ;;
    x86_64)
        core_arch="linux-amd64"
        ;;
    mips64el_*)
        core_arch="linux-mips64le"
        ;;
    mips64_*)
        core_arch="linux-mips64"
        ;;
    mipsel_*)
        core_arch="linux-mipsle-softfloat"
        ;;
    mips_*)
        core_arch="linux-mips-softfloat"
        ;;
    riscv64_*)
        core_arch="linux-riscv64"
        ;;
    loongarch64_*|loong64_*)
        core_arch="linux-loong64-abi1"
        ;;
    *)
        core_arch="0"
        ;;
esac
uci -q set nikki.config.core_version="$core_arch"

uci -q batch <<-EOF > /dev/null
	del firewall.nikki
	set firewall.nikki=include
	set firewall.nikki.type=script
	set firewall.nikki.fw4_compatible=1
	set firewall.nikki.path=$FIREWALL_INCLUDE_SH
	commit nikki
	commit firewall
EOF

rm -f /tmp/luci-*

exit 0
