#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1
PROG="/usr/bin/mihomo"
. "$IPKG_INSTROOT/etc/nikki/scripts/include.sh"

extra_command 'clear_logs' 'Clear logs if size exceeds the limit'
extra_command 'update_subscription' 'Update subscription by section id'

boot() {
	config_load nikki
	local enabled start_delay
	config_get_bool enabled "config" "enabled" 0
	config_get  start_delay "config" "start_delay" 0
	if [ "$enabled" = 1 -a "$start_delay" -gt 0 ]; then
		log "App" "Start after %s seconds." "$start_delay"
		sleep "$start_delay"
	fi
	start
}

start_service() {
	config_load nikki
	local enabled
	config_get_bool enabled config enabled 0
	if [ "$enabled" = 0 ]; then
		log "App" "Disabled."
		log "App" "Exit."
		return
	fi

	if [ ! -x $PROG ]; then
		log "App" "Core is not executable."
		log "App" "Exit."
		return
	fi

	log "App" "Enabled."
	log "App" "Start."

	local hosts sniffer_sniff authentication tun_dns_hijack fake_ip_filter dns_nameserver \
		  force_domain_name ignore_domain_name dns_nameserver_policy
	config_get_bool hosts                 "mixin" "hosts"                      0
	config_get_bool sniffer_sniff         "mixin" "sniffer_sniff"              0
	config_get_bool authentication        "mixin" "authentication"             0
	config_get_bool tun_dns_hijack        "mixin" "tun_dns_hijack"             0
	config_get_bool fake_ip_filter        "mixin" "fake_ip_filter"             0
	config_get_bool dns_nameserver        "mixin" "dns_nameserver"             0
	config_get_bool force_domain_name     "mixin" "sniffer_force_domain_name"  0
	config_get_bool ignore_domain_name    "mixin" "sniffer_ignore_domain_name" 0
	config_get_bool dns_nameserver_policy "mixin" "dns_nameserver_policy"      0

	local tun_listener_name tproxy_listener_name redirect_listener_name
	config_get tun_listener_name      "core" "tun_listener_name"
	config_get tproxy_listener_name   "core" "tproxy_listener_name"
	config_get redirect_listener_name "core" "redirect_listener_name"

	local tcp_mode udp_mode proxy_enabled ipv4_dns_hijack ipv6_dns_hijack
	config_get      tcp_mode        "proxy" "tcp_mode"
	config_get      udp_mode        "proxy" "udp_mode"
	config_get_bool proxy_enabled   "proxy" "enabled"         0
	config_get_bool ipv4_dns_hijack "proxy" "ipv4_dns_hijack" 0
	config_get_bool ipv6_dns_hijack "proxy" "ipv6_dns_hijack" 0

	local profile core_only test_profile
	config_get      profile      "config" "profile"
	config_get_bool core_only    "config" "core_only"         0
	config_get_bool test_profile "config" "test_profile"      0

	if [ "${profile%%:*}" = "file" ]; then
		local profile_name; profile_name="${profile#*:}"
		local profile_file; profile_file="$PROFILES_DIR/$profile_name"
		log "Profile" "Use file: %s." "$profile_name"
		if [ ! -f "$profile_file" ]; then
			log "Profile" "File not found."
			log "App" "Exit."
			return
		fi
		cp -f "$profile_file" "$TEMP_CONFIG"
	elif [ "${profile%%:*}" = "subscription" ]; then
		local name prefer section="${profile#*:}"
		config_get name   "$section" "name"
		config_get prefer "$section" "prefer" "remote"
		log "Profile" "Use subscription: %s." "$name"
		local subscription_file; subscription_file="$SUBSCRIPTIONS_DIR/$name.yaml"
		if [ "$prefer" = "remote" -o ! -f "$subscription_file" ]; then
			update_subscription "$section"
		fi
		if [ ! -f "$subscription_file" ]; then
			log "Profile" "Subscription file not found."
			log "App" "Exit."
			return
		fi
		cp -f "$subscription_file" "$TEMP_CONFIG"
	else
		log "Profile" "No profile/subscription selected."
		log "App" "Exit."
		return
	fi

	if [ "$core_only" = 0 ]; then
		[ "$hosts"                 = 1 ] && yq -Mi 'del(.hosts)'                 "$TEMP_CONFIG"
		[ "$sniffer_sniff"         = 1 ] && yq -Mi 'del(.sniffer.sniff)'         "$TEMP_CONFIG"
		[ "$authentication"        = 1 ] && yq -Mi 'del(.authentication)'        "$TEMP_CONFIG"
		[ "$tun_dns_hijack"        = 1 ] && yq -Mi 'del(.tun.dns-hijack)'        "$TEMP_CONFIG"
		[ "$fake_ip_filter"        = 1 ] && yq -Mi 'del(.dns.fake-ip-filter)'    "$TEMP_CONFIG"
		[ "$force_domain_name"     = 1 ] && yq -Mi 'del(.sniffer.force-domain)'  "$TEMP_CONFIG"
		[ "$ignore_domain_name"    = 1 ] && yq -Mi 'del(.sniffer.skip-domain)'   "$TEMP_CONFIG"
		[ "$dns_nameserver_policy" = 1 ] && yq -Mi 'del(.dns.nameserver-policy)' "$TEMP_CONFIG"
		[ "$dns_nameserver"        = 1 ] && yq -Mi 'del(.dns.default-nameserver) | del(.dns.fallback) | del(.dns.proxy-server-nameserver) | del(.dns.direct-nameserver) | del(.dns.nameserver)' "$TEMP_CONFIG"

		local mixin_file file_url mixin_extra_file=""
		config_get file_url   config file_url
		config_get mixin_file config mixin_file

		[ -n "$file_url" -a x"$profile_name" != 'x' ] && \
			yq -i --yaml-fix-merge-anchor-to-spec ".proxy-providers[].url = \"$file_url\"" "$TEMP_CONFIG"

		[ -n "$mixin_file" ] && {
			mixin_extra_file="/etc/nikki/mixin/$mixin_file"
			log "Mixin" "%s Mixin config." "$mixin_file"
		}

		ucode -S "/etc/nikki/ucode/mixin.uc" | yq -P -oy | yq -i --yaml-fix-merge-anchor-to-spec eval-all '
			... comments="" | . as $item ireduce ({}; . * $item ) | explode(.) |
			.proxies      = .node               + .proxies      | del(.node)               |
			.proxies      = .nikki-proxies      + .proxies      | del(.nikki-proxies)      |
			.proxy-groups = .nikki-proxy-groups + .proxy-groups | del(.nikki-proxy-groups) |
			.rules        = .nikki-rules        + .rules        | del(.nikki-rules)        |
			.rule-providers? |= with_entries(.key as $k | ((.value.path | select(. != "")) // ("./rule_provider/" + $k)) as $base | .value.path = (($base | select(test("/$")) | . + $k) // $base))
			' "$TEMP_CONFIG" $mixin_extra_file -

		if [ "$proxy_enabled" = 1 ]; then
			if yq 'has("tun")' "$TEMP_CONFIG" >/dev/null 2>&1; then
				yq -Mi '(.tun) |= (.auto-route = false | .auto-redirect = false | .auto-detect-interface = false | .disable-icmp-forwarding = true)' "$TEMP_CONFIG"
			fi
			if yq 'has("listeners")' "$TEMP_CONFIG" >/dev/null 2>&1; then
				yq -Mi '(.listeners[] | select(.type == "tun")) |= (.auto-route = false | .auto-redirect = false | .auto-detect-interface = false | .disable-icmp-forwarding = true)' "$TEMP_CONFIG"
			fi
		fi
	else
		yq -Mi '... comments="" | explode(.) |
				.tun = (.tun // {})          |
				.tun.enable = true           |
				.tun.stack = "mixed"         |
				.tun["auto-route"] = true    |
				.tun["auto-redirect"] = true |
				.tun["auto-detect-interface"] = true
				' "$TEMP_CONFIG"
	fi

	if [ "$core_only" = 0 -a "$proxy_enabled" = 1 ]; then
		# log "Profile" "Checking..."
		if [ "$ipv4_dns_hijack" = 1 -o "$ipv6_dns_hijack" = 1 ]; then
			if ! yq '(has("dns") and (.dns | .enable) and (.dns | has("listen")))' "$TEMP_CONFIG" >/dev/null 2>&1; then
				log "Profile" "Check failed."
				log "Profile" "DNS should be enabled and listen should be defined."
				log "App" "Exit."
				return
			fi
		fi
		if [ "$tcp_mode" = "redirect" ]; then
			if yq -Me "(has(\"redir-port\") or (has(\"listeners\") and .listeners | any_c(.name == \"$redirect_listener_name\" and .type == \"redir\"))) | not" "$TEMP_CONFIG" > /dev/null 2>&1; then
				log "Profile" "Check failed."
				log "Profile" "Redirect Port/Listener should be defined."
				log "App" "Exit."
				return
			fi
		fi
		if [ "$tcp_mode" = "tproxy" -o "$udp_mode" = "tproxy" ]; then
			if yq -Me "(has(\"tproxy-port\") or (has(\"listeners\") and .listeners | any_c(.name == \"$tproxy_listener_name\" and .type == \"tproxy\"))) | not" "$TEMP_CONFIG" > /dev/null 2>&1; then
				log "Profile" "Check failed."
				log "Profile" "TPROXY Port/Listener should be defined."
				log "App" "Exit."
				return
			fi
		fi
		if [ "$tcp_mode" = "tun" -o "$udp_mode" = "tun" ]; then
			if yq -Me "(has(\"tun\") and (.tun | .enable) and (.tun | has(\"device\"))) or (has(\"listeners\") and .listeners | any_c(.name == \"$tun_listener_name\" and .type == \"tun\" and has(\"device\")))) | not" "$TEMP_CONFIG" > /dev/null 2>&1; then
				log "Profile" "Check failed."
				log "Profile" "TUN should be defined."
				log "App" "Exit."
				return
			fi
		fi
		# log "Profile" "Check passed."
	fi
	mv -f "$TEMP_CONFIG" "$RUN_PROFILE_PATH"

	if [ "$test_profile" = 1 ]; then
		log "Profile" "Testing..."
		if $PROG -d "$RUN_DIR" -t >> "$CORE_LOG_PATH" 2>&1; then
			log "Profile" "Test passed."
		else
			log "Profile" "Test failed."
			log "Profile" "Please check the core log to find out the problem."
			log "App" "Exit."
			return
		fi
	fi

	log "Core" "Start."
	local go_max_procs go_mem_limit safe_paths disable_loopback_detector disable_quic_go_gso \
		  disable_quic_go_ecn skip_system_ipv6_check fast_reload nproc_soft nproc_hard address_space_soft \
		  address_space_hard data_soft data_hard stack_soft stack_hard nofile_soft nofile_hard
	config_get      safe_paths                "procd" "safe_paths"
	config_get      go_max_procs              "procd" "go_max_procs"
	config_get      go_mem_limit              "procd" "go_mem_limit"
	config_get      data_soft                 "procd" "data_soft"
	config_get      data_hard                 "procd" "data_hard"
	config_get      stack_soft                "procd" "stack_soft"
	config_get      stack_hard                "procd" "stack_hard"
	config_get      address_space_soft        "procd" "address_space_soft"
	config_get      address_space_hard        "procd" "address_space_hard"
	config_get      nproc_soft                "procd" "nproc_soft"  "$(ulimit -Su)"
	config_get      nproc_hard                "procd" "nproc_hard"  "$(ulimit -Hu)"
	config_get      nofile_soft               "procd" "nofile_soft" "$(ulimit -Sn)"
	config_get      nofile_hard               "procd" "nofile_hard" "$(ulimit -Hn)"
	config_get_bool fast_reload               "procd" "fast_reload"               0
	config_get_bool disable_quic_go_gso       "procd" "disable_quic_go_gso"       0
	config_get_bool disable_quic_go_ecn       "procd" "disable_quic_go_ecn"       0
	config_get_bool skip_system_ipv6_check    "procd" "skip_system_ipv6_check"    0
	config_get_bool disable_loopback_detector "procd" "disable_loopback_detector" 0

	procd_open_instance nikki
	procd_set_param command /bin/sh -c "$PROG -d $RUN_DIR >> $CORE_LOG_PATH 2>&1"
	procd_set_param file "$RUN_PROFILE_PATH"
	procd_set_param pidfile "$PID_FILE_PATH"
	[ "$fast_reload" = 1 ] && procd_set_param reload_signal HUP
	procd_set_param respawn

	procd_append_param env SAFE_PATHS="$safe_paths"
	procd_append_param env GOMAXPROCS="$go_max_procs"
	procd_append_param env GOMEMLIMIT="$go_mem_limit"
	procd_append_param env QUIC_GO_DISABLE_GSO="$disable_quic_go_gso"
	procd_append_param env QUIC_GO_DISABLE_ECN="$disable_quic_go_ecn"
	procd_append_param env SKIP_SYSTEM_IPV6_CHECK="$skip_system_ipv6_check"
	procd_append_param env DISABLE_LOOPBACK_DETECTOR="$disable_loopback_detector"

	procd_append_param limits nproc="${nproc_soft} ${nproc_hard}"
	procd_append_param limits nofile="${nofile_soft} ${nofile_hard}"
	procd_append_param limits data="${data_soft:-unlimited} ${data_hard:-unlimited}"
	procd_append_param limits stack="${stack_soft:-unlimited} ${stack_hard:-unlimited}"
	procd_append_param limits as="${address_space_soft:-unlimited} ${address_space_hard:-unlimited}"

	procd_close_instance

	local log_scheduled_clear log_scheduled_clear_cron scheduled_restart scheduled_restart_cron  reload_cron=0
	config_get      log_scheduled_clear_cron "log" "scheduled_clear_cron"
	config_get_bool log_scheduled_clear      "log" "scheduled_clear" 0
	config_get      scheduled_restart_cron "config" "scheduled_restart_cron"
	config_get_bool scheduled_restart      "config" "scheduled_restart" 0

	if [ "$scheduled_restart" = 1 -a -n "$scheduled_restart_cron" ]; then
		log "App" "Set scheduled restart."
		echo "$scheduled_restart_cron /etc/init.d/nikki restart #nikki scheduled restart" >> "/etc/crontabs/root"
		reload_cron=1
	fi
	if [ "$log_scheduled_clear" = 1 -a -n "$log_scheduled_clear_cron" ]; then
		log "App" "Set log scheduled clear."
		echo "$log_scheduled_clear_cron /etc/init.d/nikki clear_logs #nikki log scheduled clear" >> "/etc/crontabs/root"
		reload_cron=1
	fi
	[ "$reload_cron" = 1 ] && /etc/init.d/cron restart
	touch "$STARTED_FLAG_PATH"
}

service_started() {
	[ -f "$STARTED_FLAG_PATH" ] || return

	config_load nikki
	local proxy_enabled
	config_get_bool proxy_enabled "proxy" "enabled" 0
	if [ "$proxy_enabled" = 0 ]; then
		log "Proxy" "Disabled."
		return
	fi

	local core_only tun_listener_name
	config_get_bool core_only "config" "core_only" 0
	config_get tun_listener_name "core" "tun_listener_name"

	local tcp_mode udp_mode tun_timeout tun_interval ipv4_proxy ipv6_proxy
	config_get tcp_mode     "proxy" "tcp_mode"
	config_get udp_mode     "proxy" "udp_mode"
	config_get tun_timeout  "proxy" "tun_timeout"   30
	config_get tun_interval "proxy" "tun_interval"  1
	config_get_bool ipv4_proxy "proxy" "ipv4_proxy" 0
	config_get_bool ipv6_proxy "proxy" "ipv6_proxy" 0

	local tproxy_fw_mark tproxy_fw_mask tun_fw_mark tun_fw_mask tproxy_rule_pref tun_rule_pref \
		  tproxy_route_table tun_route_table cgroup_id cgroup_name dummy_device
	config_get tproxy_fw_mark     "routing" "tproxy_fw_mark"     "0x80"
	config_get tproxy_fw_mask     "routing" "tproxy_fw_mask"     "0xFF"
	config_get tun_fw_mark        "routing" "tun_fw_mark"        "0x81"
	config_get tun_fw_mask        "routing" "tun_fw_mask"        "0xFF"
	config_get tproxy_rule_pref   "routing" "tproxy_rule_pref"   "1024"
	config_get tun_rule_pref      "routing" "tun_rule_pref"      "1025"
	config_get tproxy_route_table "routing" "tproxy_route_table" "80"
	config_get tun_route_table    "routing" "tun_route_table"    "81"
	config_get cgroup_id          "routing" "cgroup_id"          "0x12061206"
	config_get cgroup_name        "routing" "cgroup_name"        "nikki"
	config_get dummy_device       "routing" "dummy_device"       "nikki-dummy"

	local tproxy_enable=0 tun_enable=0
	[ "$tcp_mode" = "tun"    -o "$udp_mode" = "tun"    ] && tun_enable=1
	[ "$tcp_mode" = "tproxy" -o "$udp_mode" = "tproxy" ] && tproxy_enable=1

	local dns_mode; dns_mode=$(yq -M '.dns.enhanced-mode // ""' "$RUN_PROFILE_PATH")
	local fake_ip6_range; fake_ip6_range=$(yq -M '.dns.fake-ip-range6 // ""' "$RUN_PROFILE_PATH")
	local tun_device; tun_device=$(yq -M "(.tun | select(.enable) | .device) // (.listeners[] | select(.name == \"$tun_listener_name\" and .type == \"tun\") | .device)" "$RUN_PROFILE_PATH")
	if [ "$core_only" = 0 ]; then
		log "Proxy" "Enabled."
		if [ "$tun_enable" = 1 ]; then
			log "Proxy" "Waiting for tun device online within %s seconds..." "$tun_timeout"
			while [ "$tun_timeout" -gt 0 ]; do
				if ip -j link show dev "$tun_device" 2>/dev/null | jsonfilter -q -e "@[@['flags'][@='UP']]" > /dev/null 2>&1; then
					log "Proxy" "TUN device is online."
					break
				fi
				tun_timeout=$((tun_timeout - tun_interval))
				sleep "$tun_interval"
			done
			if [ "$tun_timeout" -le 0 ]; then
				log "Proxy" "Timeout, TUN device is not online."
				log "App" "Exit."
				return
			fi
		fi

		if mount | grep -q -w "^cgroup"; then
			mkdir -p "/sys/fs/cgroup/net_cls/$cgroup_name"
			echo "$cgroup_id" > "/sys/fs/cgroup/net_cls/$cgroup_name/net_cls.classid"
			cat "$PID_FILE_PATH" > "/sys/fs/cgroup/net_cls/$cgroup_name/cgroup.procs"
		fi

		if [ "$tproxy_enable" = 1 ] && (lsmod | grep -q br_netfilter); then
			if [ "$ipv4_proxy" = 1 ]; then
				local bridge_nf_call_iptables; bridge_nf_call_iptables=$(sysctl -e -n net.bridge.bridge-nf-call-iptables)
				if [ "$bridge_nf_call_iptables" = 1 ]; then
					touch "$BRIDGE_NF_CALL_IPTABLES_FLAG_PATH"
					sysctl -q -w net.bridge.bridge-nf-call-iptables=0
				fi
			fi
			if [ "$ipv6_proxy" = 1 ]; then
				local bridge_nf_call_ip6tables; bridge_nf_call_ip6tables=$(sysctl -e -n net.bridge.bridge-nf-call-ip6tables)
				if [ "$bridge_nf_call_ip6tables" = 1 ]; then
					touch "$BRIDGE_NF_CALL_IP6TABLES_FLAG_PATH"
					sysctl -q -w net.bridge.bridge-nf-call-ip6tables=0
				fi
			fi
		fi

		if [ "$tproxy_enable" = 1 ]; then
			if [ "$ipv4_proxy" = 1 ]; then
				ip -4 route add local default dev lo table "$tproxy_route_table"
				ip -4 rule add pref "$tproxy_rule_pref" fwmark "$tproxy_fw_mark/$tproxy_fw_mask" table "$tproxy_route_table"
			fi
			if [ "$ipv6_proxy" = 1 ]; then
				ip -6 route add local default dev lo table "$tproxy_route_table"
				ip -6 rule add pref "$tproxy_rule_pref" fwmark "$tproxy_fw_mark/$tproxy_fw_mask" table "$tproxy_route_table"
			fi
		fi
		if [ "$tun_enable" = 1 ]; then
			if [ "$ipv4_proxy" = 1 ]; then
				ip -4 route add unicast default dev "$tun_device" table "$tun_route_table"
				ip -4 rule add pref "$tun_rule_pref" fwmark "$tun_fw_mark/$tun_fw_mask" table "$tun_route_table"
			fi
			if [ "$ipv6_proxy" = 1 ]; then
				ip -6 route add unicast default dev "$tun_device" table "$tun_route_table"
				ip -6 rule add pref "$tun_rule_pref" fwmark "$tun_fw_mark/$tun_fw_mask" table "$tun_route_table"
			fi
			$FIREWALL_INCLUDE_SH
		fi
		if [ "$dns_mode" = "fake-ip" -a -n "$fake_ip6_range" ]; then
			ip link add "$dummy_device" type dummy
			ip link set dev "$dummy_device" up
			ip -6 route add "$fake_ip6_range" dev "$dummy_device"
		fi

		utpl -S "$HIJACK_UT" | nft -f -

		if nft list tables | grep -q nikki; then
			log "Proxy" "Hijack successful."
		else
			log "Proxy" "Hijack failed."
			log "App" "Exit."
		fi
	fi
}

service_stopped() {
	cleanup
}

reload_service() {
	cleanup
	start
}

service_triggers() {
	procd_add_reload_trigger "nikki"
}

cleanup() {
	config_load nikki
	local log_clear_at_stop dummy_device tun_route_table tproxy_route_table
	config_get_bool log_clear_at_stop "log" "clear_at_stop" 0
	config_get dummy_device       "routing" "dummy_device"       "nikki-dummy"
	config_get tun_route_table    "routing" "tun_route_table"    "81"
	config_get tproxy_route_table "routing" "tproxy_route_table" "80"

	if [  "$log_clear_at_stop" = 1 ]; then
		> "$APP_LOG_PATH"
		> "$CORE_LOG_PATH"
		log "Log" "Logs are cleared due to clear at stop is enabled."
	fi

	ip -4 rule del table "$tproxy_route_table" > /dev/null 2>&1
	ip -4 rule del table "$tun_route_table" > /dev/null 2>&1
	ip -6 rule del table "$tproxy_route_table" > /dev/null 2>&1
	ip -6 rule del table "$tun_route_table" > /dev/null 2>&1

	ip -4 route flush table "$tproxy_route_table" > /dev/null 2>&1
	ip -4 route flush table "$tun_route_table" > /dev/null 2>&1
	ip -6 route flush table "$tproxy_route_table" > /dev/null 2>&1
	ip -6 route flush table "$tun_route_table" > /dev/null 2>&1

	ip -6 link del "$dummy_device" > /dev/null 2>&1

	nft delete table inet nikki > /dev/null 2>&1
	local handles handle
	handles=$(nft --json list table inet fw4 | jsonfilter -q -e "@.nftables[@.rule.chain='input' && @.rule.comment='nikki'].rule.handle")
	for handle in $handles; do
		nft delete rule inet fw4 input handle "$handle"
	done
	handles=$(nft --json list table inet fw4 | jsonfilter -q -e "@.nftables[@.rule.chain='forward' && @.rule.comment='nikki'].rule.handle")
	for handle in $handles; do
		nft delete rule inet fw4 forward handle "$handle"
	done

	rm "$STARTED_FLAG_PATH" > /dev/null 2>&1

	if rm "$BRIDGE_NF_CALL_IPTABLES_FLAG_PATH" > /dev/null 2>&1; then
		sysctl -q -w net.bridge.bridge-nf-call-iptables=1
	fi
	if rm "$BRIDGE_NF_CALL_IP6TABLES_FLAG_PATH" > /dev/null 2>&1; then
		sysctl -q -w net.bridge.bridge-nf-call-ip6tables=1
	fi

	sed -i "/#nikki/d" "/etc/crontabs/root" > /dev/null 2>&1
	/etc/init.d/cron restart
}

clear_logs() {
	config_load nikki
	local limit limit_unit limit_bytes=0
	config_get limit      "log" "limit" 1
	config_get limit_unit "log" "limit_unit" "MB"

	case "$limit_unit" in
		KB) limit_bytes=$((limit * 1024)) ;;
		MB) limit_bytes=$((limit * 1024 * 1024)) ;;
		GB) limit_bytes=$((limit * 1024 * 1024 * 1024)) ;;
	esac

	[ -f "$APP_LOG_PATH" ] && [ $(wc -c < "$APP_LOG_PATH") -ge "$limit_bytes" ] && {
		> "$APP_LOG_PATH"
		log "Log" "App log is cleared due to scheduled clear and exceeding size limits."
	}

	[ -f "$CORE_LOG_PATH" ] && [ $(wc -c < "$CORE_LOG_PATH") -ge "$limit_bytes" ] && {
		> "$CORE_LOG_PATH"
		log "Log" "Core log is cleared due to scheduled clear and exceeding size limits."
	}
}

update_subscription() {
	local section="$1"
	[ x"$section" = 'x' ] && return

	config_load nikki
	local success=0 url name opt info_url user_agent file header_tmpfile info_header_tmpfile info_file
	config_get url        "$section" url
	config_get name       "$section" name
	config_get info_url   "$section" info_url
	config_get user_agent "$section" user_agent
	log "Profile" "Update subscription: %s." "$name"

	file="$SUBSCRIPTIONS_DIR/$name.yaml"
	header_tmpfile="$TEMP_DIR/$section.header"
	info_header_tmpfile="$TEMP_DIR/$section.info.header"

	if [ -n "$info_url" ]; then
		log "Profile" "Fetch subscription info."
		if curl -sfL --max-time 120 --connect-timeout 15 --retry 3 -A "$user_agent" -D "$info_header_tmpfile" "$info_url" > /dev/null 2>&1; then
			if [ ! -f "$info_file" ] && grep -q -i "subscription-userinfo:" "$info_header_tmpfile"; then
				info_file="$info_header_tmpfile"
			fi
		fi
	fi

	log "Profile" "Download subscription."
	if curl -sfL --max-time 120 --connect-timeout 15 --retry 3 -A "$user_agent" -D "$header_tmpfile" -o "$TEMP_CONFIG" "$url" > /dev/null 2>&1; then
		log "Profile" "Subscription download successful."
		if [ ! -f "$info_file" ] && grep -q -i "subscription-userinfo:" "$header_tmpfile"; then
			info_file="$header_tmpfile"
		fi
		if yq -r 'has("proxies") or has("proxy-providers")' "$TEMP_CONFIG" > /dev/null 2>&1; then
			success=1
			log "Profile" "Subscription is valid."
		else
			log "Profile" "Subscription is not valid."
		fi
	else
		log "Profile" "Subscription download failed."
	fi
	if [ "$success" = 1 ]; then
		# for opt in expire upload download total used avaliable update success; do
		# 	uci_remove nikki "$section" "$opt" > /dev/null 2>&1
		# done
		log "Profile" "Subscription update successful."
		if [ -f "$info_file" ]; then
			local userinfo expire upload download total used avaliable
			userinfo=$(grep -i "subscription-userinfo: " "$info_file")
			total=$(echo    "$userinfo" | sed -En 's/.*total=([0-9]*).*/\1/p')
			expire=$(echo   "$userinfo" | sed -En 's/.*expire=([0-9]*).*/\1/p')
			upload=$(echo   "$userinfo" | sed -En 's/.*upload=([0-9]*).*/\1/p')
			download=$(echo "$userinfo" | sed -En 's/.*download=([0-9]*).*/\1/p')

			if [ -n "$upload" -a -n "$download" ]; then
				used=$((upload + download))
				# [ -n "$total" ] && avaliable=$((total - used))
			fi

			[ -n "$used" ]      && uci_set nikki "$section" used      "$(format_filesize "$used")"
			[ -n "$total" ]     && uci_set nikki "$section" total     "$(format_filesize "$total")"
			# [ -n "$upload" ]    && uci_set nikki "$section" upload    "$(format_filesize "$upload")"
			# [ -n "$download" ]  && uci_set nikki "$section" download  "$(format_filesize "$download")"
			# [ -n "$avaliable" ] && uci_set nikki "$section" avaliable "$(format_filesize "$avaliable")"
			[ -n "$expire" ]    && uci_set nikki "$section" expire    "$(date "+%Y-%m-%d %H:%M:%S" -d "@$expire")"
		fi
		uci_set nikki "$section" update "$(date "+%Y-%m-%d %H:%M:%S")"
		mv -f "$TEMP_CONFIG" "$file"
	else
		log "Profile" "Subscription update failed."
		rm -f "$TEMP_CONFIG"
	fi

	rm -f "$header_tmpfile" "$info_header_tmpfile"
	uci_commit nikki
	[ "$success" = 1 ] && return 0 || return 1
}
