#!/bin/sh /etc/rc.common

START=99
STOP=10

hash_value() { echo "$1" | md5sum | awk '{print $1}'; }

do_network() {
	do_lan() {
		case "$lan_proto" in
			static)
				uci -q batch <<-EOF
					del dhcp.lan.ra
					del dhcp.lan.ra_slaac
					del dhcp.lan.ra_flags
					del dhcp.lan.dhcpv6
					del dhcp.lan.max_valid_lifetime
					del dhcp.lan.max_preferred_lifetime
					set dhcp.lan.ignore='1'

					set network.lan.proto='static'
					set network.lan.device='br-lan'
					set network.lan.ipaddr='$lan_ip'
					set network.lan.netmask='255.255.255.0'
					set network.lan.gateway='$gateway'
					del network.lan.ip6assign
					set network.lan.multipath='off'
					del network.lan.dns
					add_list network.lan.dns='$gateway'
					del firewall.@zone[0].network
					set network.@device[0].stp='1'
				EOF
				;;
			dhcp)
				uci -q batch <<-EOF
					del dhcp.lan.ra
					del dhcp.lan.ra_slaac
					del dhcp.lan.ra_flags
					del dhcp.lan.dhcpv6
					del dhcp.lan.max_valid_lifetime
					del dhcp.lan.max_preferred_lifetime
					set dhcp.lan.ignore='1'
					del network.lan.ipaddr
					del network.lan.netmask
					del network.lan.ip6assign
					set network.lan.proto='dhcp'
				EOF
				;;
			none)
				uci -q batch <<-EOF
					del network.lan
					set network.lan=interface
					set network.lan.proto='static'
					set network.lan.device='br-lan'
					set network.lan.ipaddr='$old_lan_ip'
					set network.lan.netmask='255.255.255.0'
					add_list firewall.@zone[0].network='lan'
					del dhcp.lan.ignore
					set dhcp.lan.ra_slaac='1'
					set dhcp.lan.ra='server'
					set dhcp.lan.max_preferred_lifetime='2700'
					set dhcp.lan.max_valid_lifetime='5400'
					del mesh_node.main.old_lan_ip
					del network.@device[0].stp
				EOF
				;;
		esac
	}

	do_wan() {
		local wan_device; wan_device="$(jsonfilter -i /etc/board.json -e '@.network.wan.device')"
		uci -q del network.wan
		uci -q del_list network.@device[0].ports='wan'
		case "$wan_proto" in
			pppoe)
				local cur_user; cur_user=$(uci -q get network.wan.username)
				local cur_pass; cur_pass=$(uci -q get network.wan.password)
				([ "$cur_user" != "$user" ] || [ "$cur_pass" != "$pass" ]) && \
				uci -q batch <<-EOF
					set network.wan=interface
					set network.wan.device="${wan_device:=wan}"
					set network.wan.proto='pppoe'
					set network.wan.username='$user'
					set network.wan.password='$pass'
				EOF
				;;
			dhcp)
				uci -q batch <<-EOF
					set network.wan=interface
					set network.wan.device="${wan_device:=wan}"
					set network.wan.proto='dhcp'
				EOF
				;;
			bridge)
				uci -q batch <<-EOF
					del network.wan6
					add_list network.@device[0].ports='wan'
				EOF
				;;
		esac
	}

	local lan_hash old_lan_hash wan_hash old_wan_hash old_lan_ip changed=0
	wan_hash=$(hash_value "${wan_proto}:${user}:${pass}:${combo_mode}")
	lan_hash=$(hash_value "${lan_proto}:${lan_ip}:${gateway}:${combo_mode}")
	config_get old_lan_ip   main old_lan_ip   ''
	config_get old_lan_hash main old_lan_hash ''
	config_get old_wan_hash main old_wan_hash ''

	[ -n "$old_lan_ip" ] || uci -q set mesh_node.main.old_lan_ip="$(uci -q get network.lan.ipaddr)"
	[ "$lan_hash" = "$old_lan_hash" ] || { do_lan; changed=1; }
	[ "$wan_hash" = "$old_wan_hash" ] || { do_wan; changed=1; }
	[ "$changed" -eq 0 ] && return 1
	uci -q set mesh_node.main.old_lan_hash="$lan_hash"
	uci -q set mesh_node.main.old_wan_hash="$wan_hash"
	return 0
}

do_wireless() {
	local iface_mac; iface_mac=$(cat /sys/class/net/br-lan/address 2>/dev/null | tr -d ':')
	[ -z "$iface_mac" ] && iface_mac=$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d ':')
	iface_mac="${iface_mac:=000000000000}"
	wifi_iface() {
		local iface="$1" dev band mode
		config_get mode "$iface" mode
		[ "$mode" = "ap" ] || return
		config_get dev  "$iface" device
		config_get band "$dev"   band
		eval "key=\$key_${band} ssid=\$ssid_${band}"
		uci -q set wireless."$iface".key="${wifi_pass:-$key}"
		uci -q set wireless."$iface".ssid="${wifi_ssid:-$ssid}"

		uci -q batch <<-EOF
			set wireless.${iface}.disabled='0'
			set wireless.${iface}.proxy_arp='1'
			set wireless.${iface}.ieee80211k='1'
			set wireless.${iface}.ieee80211r='1'
			set wireless.${iface}.ft_over_ds='0'
			set wireless.${iface}.nasid='${iface_mac}'
			set wireless.${iface}.mobility_domain='55ff'
			set wireless.${iface}.encryption='psk2'
			set wireless.${iface}.ft_psk_generate_local='0'
			set wireless.${iface}.bss_transition='1'
			set wireless.${iface}.r1_key_holder='9f8e7d6c5b4a'
		EOF
	}

	wifi_device() {
		local dev="$1" band mesh_fwding=1
		local mesh_iface="mesh_${dev}"
		config_get band "$dev" band
		local mesh_ifname="phy${dev#radio}-mesh0"
		uci -q del wireless.${mesh_iface}
		uci -q set wireless."$dev".disabled='0'
		uci -q set wireless."$dev".cell_density='0'
		uci -q set wireless."$dev".log_level="${log_level}"

		[ "$mesh_radio" != "none" ] && [ "$mesh_radio" != "$band" ] && return 0

		[ "$use_batadv" = "1" ] && mesh_fwding=0

		uci -q batch <<-EOF
			set wireless.${mesh_iface}='wifi-iface'
			set wireless.${mesh_iface}.device='${dev}'
			set wireless.${mesh_iface}.mode='mesh'
			set wireless.${mesh_iface}.network='${batadv_hardif:-$mesh_network}'
			set wireless.${mesh_iface}.mesh_fwding='${mesh_fwding}'
			set wireless.${mesh_iface}.mesh_ttl='31'
			set wireless.${mesh_iface}.encryption='sae'
			set wireless.${mesh_iface}.key='${mesh_pass}'
			set wireless.${mesh_iface}.mesh_id='${mesh_id}'
			set wireless.${mesh_iface}.ifname='${mesh_ifname}'
			set wireless.${mesh_iface}.mesh_rssi_threshold='0'
		EOF
	}

	[ "$band_mode" = "2" ] && return
	config_get key_2g        main key_2g          ''
	config_get ssid_2g       main ssid_2g         ''
	config_get key_5g        main key_5g          ''
	config_get ssid_5g       main ssid_5g         ''
	config_get key_6g        main key_6g          ''
	config_get ssid_6g       main ssid_6g         ''
	config_get wifi_pass     main wifi_pass       ''
	config_get wifi_ssid     main wifi_ssid       ''
	config_get log_level     main log_level       ''
	local mesh_hash old_mesh_hash radio_hash old_radio_hash changed=0
	mesh_hash=$(hash_value "${mesh_id}:${mesh_pass}:${mesh_radio}:${mesh_network}:${use_batadv}:${log_level}")
	radio_hash=$(hash_value "${ssid_2g}:${key_2g}:${ssid_5g}:${key_5g}:${ssid_6g}:${key_6g}:${wifi_pass}:${wifi_ssid}")

	config_get old_mesh_hash  main old_mesh_hash  ''
	config_get old_radio_hash main old_radio_hash ''

	config_load wireless
	[ "$radio_hash" != "$old_radio_hash" ] && { config_foreach wifi_iface  wifi-iface;  changed=1; }
	[ "$mesh_hash"  != "$old_mesh_hash"  ] && { config_foreach wifi_device wifi-device; changed=1; }
	uci -q set mesh_node.main.old_mesh_hash="$mesh_hash"
	uci -q set mesh_node.main.old_radio_hash="$radio_hash"
	config_load mesh_node
	[ "$changed" -eq 0 ] && return
	wireless_changed=1
}

do_batadv() {
	local old_use_batadv bat0_in_bridge
	config_get old_use_batadv main old_use_batadv  ''
	[ "$use_batadv" = "$old_use_batadv" ] && return 1
	uci -q set mesh_node.main.old_use_batadv="$use_batadv"

	if [ "$use_batadv" = "1" ]; then
		modprobe batman-adv 2>/dev/null || true
		bat0_in_bridge=$(uci -q show network.@device[0].ports 2>/dev/null | grep -c "$batadv_proto")
		[ "${bat0_in_bridge:-0}" -eq 0 ] && \
			uci -q add_list network.@device[0].ports="$batadv_proto"
	else
		cleanup_batman() {
			local iface="$1" proto
			config_get proto "$iface" proto
			if [ "$proto" = 'batadv' ] || [ "$proto" = 'batadv_hardif' ]; then
				uci -q del network."$iface"
				uci -q del_list network.@device[0].ports="$iface" 2>/dev/null
			fi
		}
		config_load network
		config_foreach cleanup_batman interface
		rmmod batman-adv 2>/dev/null
		config_load mesh_node
	fi
	return 0
}

do_services() {
	handle_old_service() {
		local svc="$1"
		echo "$init" | grep -qw "$svc" && return
		[ -x "/etc/init.d/$svc" ] && {
			/etc/init.d/$svc start   2>/dev/null
			/etc/init.d/$svc enable  2>/dev/null
		}
		uci -q del_list mesh_node.main.old_init="$svc"
	}
	handle_new_service() {
		local svc="$1"
		echo "$old_init" | grep -qw "$svc" && return
		/etc/init.d/$svc running 2>/dev/null && /etc/init.d/$svc stop    2>/dev/null
		/etc/init.d/$svc enabled 2>/dev/null && /etc/init.d/$svc disable 2>/dev/null
		uci -q add_list mesh_node.main.old_init="$svc"
	}
	config_list_foreach main old_init handle_old_service
	config_list_foreach main init     handle_new_service
}

do_mesh11sd() {
	local m11_hash; m11_hash=$(hash_value "$(uci -q show mesh11sd)")
	config_get old_m11_hash main old_m11_hash ''
	[ "$m11_hash" = "$old_m11_hash" ] && return 1
	uci -q set mesh11sd.setup.enabled="${m11_enable}"
	uci -q set mesh_node.main.old_m11_hash="$m11_hash"
	return 0
}

do_usteer() {
	local usteer_hash old_usteer_hash
	usteer_hash=$(hash_value "$(uci -q show usteer)")
	config_get old_usteer_hash main old_usteer_hash ''
	[ "$usteer_hash" = "$old_usteer_hash" ] && return 1
	uci -q set usteer.@usteer[0].enabled="${enable_usteer}"
	uci -q set mesh_node.main.old_usteer_hash="$usteer_hash"
	return 0
}

start() {
	local combo_mode wan_proto lan_proto lan_ip gateway user pass log_level \
		  ssid_2g ssid_5g key_2g key_5g wifi_ssid wifi_pass mesh_id mesh_pass \
		  mesh_radio mesh_network enable_usteer init old_init hostname old_hostname \
		  batadv_proto batadv_hardif \
		  band_mode old_m11_hash m11_enable use_batadv usteer_changed=0 \
		  network_changed=0 wireless_changed=0 mesh11sd_changed=0

	config_load mesh_node
	config_get combo_mode    main combo_mode      ''
	config_get wan_proto     main wan_proto       ''
	config_get lan_proto     main lan_proto       ''
	config_get lan_ip        main lan_ip          ''
	config_get gateway       main gateway         ''
	config_get user          main wan_pppoe_user  ''
	config_get pass          main wan_pppoe_pass  ''

	config_get mesh_id       main mesh_id         ''
	config_get mesh_pass     main mesh_pass       ''
	config_get mesh_radio    main mesh_radio      ''
	config_get mesh_network  main mesh_network    ''
	config_get band_mode     main band_mode       '0'
	config_get batadv_proto  globals batadv_proto ''
	config_get batadv_hardif globals batadv_hardif ''

	config_get init          main init            ''
	config_get old_init      main old_init        ''
	config_get hostname      main hostname        ''
	config_get old_hostname  main old_hostname    ''

	config_get_bool use_batadv main use_batadv 0
	config_get_bool m11_enable main m11_enable 0
	config_get_bool enable_usteer globals enable_usteer 0

	[ "$hostname" != "$old_hostname" ] && {
		uci -q set system.@system[0].hostname="$hostname"
		uci -q set mesh_node.main.old_hostname="$hostname"
		uci -q commit system
		/etc/init.d/system reload
	}

	do_services
	do_wireless
	do_batadv   && network_changed=1
	do_network  && network_changed=1
	do_mesh11sd && mesh11sd_changed=1
	do_usteer   && usteer_changed=1
	uci -q commit

	[ "$network_changed"  = 1 ] && { /etc/init.d/network restart; sleep 5; }
	[ "$wireless_changed" = 1 ] && { wifi reload; sleep 3; }
	[ "$mesh11sd_changed" = 1 ] && [ "$band_mode" = "2" ] && {
		if [ "$m11_enable" = "1" ]; then
			/etc/init.d/mesh11sd enable  2>/dev/null || true
			/etc/init.d/mesh11sd restart 2>/dev/null || true
		else
			/etc/init.d/mesh11sd stop    2>/dev/null || true
			/etc/init.d/mesh11sd disable 2>/dev/null || true
		fi
	}

	[ "$usteer_changed" = 1 ] && {
		if [ "$enable_usteer" = '1' ]; then
			[ "$use_batadv" = "1" ] && sleep 10
			/etc/init.d/usteer enable  2>/dev/null || true
			/etc/init.d/usteer restart 2>/dev/null || true
		else
			/etc/init.d/usteer stop    2>/dev/null || true
			/etc/init.d/usteer disable 2>/dev/null || true
		fi
	}
}

stop() { :; }
boot() { :; }
