#!/bin/sh /etc/rc.common

START=99
STOP=10
. /lib/functions/network.sh

do_network() {
	local hash network_hash old_lan_ip
	hash=$(echo "${bridge_wan}:${lan_proto}:${lan_ip}:${gateway}:${user}:${pass}" | md5sum | awk '{print $1}')
	config_get old_lan_ip   main old_lan_ip   ''
	config_get network_hash main network_hash ''
	[ -n "$old_lan_ip" ] || uci -q set mesh_node.main.old_lan_ip=$(uci -q get network.lan.ipaddr)
	[ "$hash" = "$network_hash" ] && return 1

	case "$lan_proto" in
		static)
			uci -q batch <<-EOF
				del dhcp.lan.ra_slaac
				del dhcp.lan.ra
				del dhcp.lan.ra_flags
				del dhcp.lan.dhcpv6
				set dhcp.lan.ignore='1'
				set network.lan.proto='static'
				set network.lan.ipaddr='$lan_ip'
				set network.lan.netmask='255.255.255.0'
				set network.lan.gateway='$gateway'
				set network.lan.stp='1'
				del network.lan.dns
				add_list network.lan.dns='$gateway'
			EOF
			;;
		dhcp)
			uci -q batch <<-EOF
				del dhcp.lan.ra_slaac
				del dhcp.lan.ra
				del dhcp.lan.ra_flags
				del dhcp.lan.dhcpv6
				del dhcp.lan.max_preferred_lifetime
				del dhcp.lan.max_valid_lifetime
				set dhcp.lan.ignore='1'
				del network.lan.ipaddr
				del network.lan.netmask
				del network.lan.ip6assign
				set network.lan.proto='dhcp'
			EOF
			;;
		none)
			uci -q batch <<-EOF
				del network.lan
				set network.lan=interface
				set network.lan.proto='static'
				set network.lan.device='br-lan'
				set network.lan.ipaddr='$old_lan_ip'
				set network.lan.netmask='255.255.255.0'
				del mesh_node.main.old_lan_ip
			EOF
			;;
	esac

	local wan_device; wan_device="$(jsonfilter -i /etc/board.json -e '@.network.wan.device')"
	case "$bridge_wan" in
		pppoe)
			local cur_user cur_pass
			cur_user=$(uci -q get network.wan.username)
			cur_pass=$(uci -q get network.wan.password)
			if [ "$cur_user" != "$user" ] || [ "$cur_pass" != "$pass" ]; then
				uci -q batch <<-EOF
					del network.wan
					set network.wan=interface
					set network.wan.device="$wan_device"
					set network.wan.proto='pppoe'
					set network.wan.username='$user'
					set network.wan.password='$pass'
					del_list network.@device[0].ports='wan'
				EOF
			fi
			;;
		dhcp)
			uci -q batch <<-EOF
				del network.wan
				set network.wan=interface
				set network.wan.device="$wan_device"
				set network.wan.proto='dhcp'
				del_list network.@device[0].ports='wan'
			EOF
			;;
		bridge)
			uci -q batch <<-EOF
				del_list network.@device[0].ports='wan'
				add_list network.@device[0].ports='wan'
				del network.wan
				del network.wan6
			EOF
			;;
	esac
	uci -q set mesh_node.main.network_hash="$hash"
	return 0
}

do_wireless() {
	local hash wireless_hash
	hash=$(echo "${ssid_24g}:${ssid_5g}:${wifi_pass}:${mesh_id}:${mesh_pass}" | md5sum | awk '{print $1}')
	config_get wireless_hash main wireless_hash ''
	[ "$hash" = "$wireless_hash" ] && return 1

	local iface_mac; iface_mac=$(cat /sys/class/net/br-lan/address | tr -d ':')
	local timezone; timezone=$(uci -q get system.@system[0].timezone 2>/dev/null)
	config_load wireless

	wifi_iface() {
		local iface="$1" dev band mode
		config_get mode "$iface" mode
		[ "$mode" = "ap" ] || return
		config_get dev  "$iface" device
		config_get band "$dev"   band

		case "$band" in
			5g|5GHz|a|an)   uci -q set wireless."$iface".ssid="$ssid_5g"  ;;
			2g|2.4GHz|b|bg) uci -q set wireless."$iface".ssid="$ssid_24g" ;;
		esac

		uci -q batch <<-EOF
			set wireless.${iface}.proxy_arp='1'
			set wireless.${iface}.ieee80211k='1'
			set wireless.${iface}.ieee80211v='1'
			set wireless.${iface}.ieee80211r='1'
			set wireless.${iface}.ft_over_ds='1'
			set wireless.${iface}.bss_transition='1'
			set wireless.${iface}.key='${wifi_pass}'
			set wireless.${iface}.nasid='${iface_mac}'
			set wireless.${iface}.mobility_domain='4f57'
			set wireless.${iface}.encryption='psk2+ccmp'
			set wireless.${iface}.ft_psk_generate_local='1'
		EOF
	}

	wifi_device() {
		local dev="$1" band
		config_get band "$dev" band
		uci -q set wireless."$dev".cell_density='0'

		case "$band" in 5g|5GHz|a|an) ;; *) return ;; esac

		local mesh_iface="mesh_${dev}"
		uci -q batch <<-EOF
			del wireless.${mesh_iface}
			set wireless.${mesh_iface}='wifi-iface'
			set wireless.${mesh_iface}.mode='mesh'
			set wireless.${mesh_iface}.disabled='0'
			set wireless.${mesh_iface}.network='lan'
			set wireless.${mesh_iface}.device='${dev}'
			set wireless.${mesh_iface}.mesh_fwding='1'
			set wireless.${mesh_iface}.encryption='sae'
			set wireless.${mesh_iface}.key='${mesh_pass}'
			set wireless.${mesh_iface}.mesh_id='${mesh_id}'
			set wireless.${mesh_iface}.mesh_rssi_threshold='-65'
		EOF
	}

	config_foreach wifi_iface  wifi-iface
	config_foreach wifi_device wifi-device
	uci -q set mesh_node.main.wireless_hash="$hash"
	return 0
}

do_services() {
	handle_old_service() {
		local svc="$1"
		echo "$init" | grep -qw "$svc" && return
		[ -x "/etc/init.d/$svc" ] && {
			/etc/init.d/$svc start 2>/dev/null
			/etc/init.d/$svc enable 2>/dev/null
		}
		uci -q del_list mesh_node.main.old_init="$svc"
	}

	handle_new_service() {
		local svc="$1"
		echo "$old_init" | grep -qw "$svc" && return
		/etc/init.d/$svc running 2>/dev/null && /etc/init.d/$svc stop    2>/dev/null
		/etc/init.d/$svc enabled 2>/dev/null && /etc/init.d/$svc disable 2>/dev/null
		uci -q add_list mesh_node.main.old_init="$svc"
	}

	config_list_foreach main old_init handle_old_service
	config_list_foreach main init     handle_new_service
}

start() {
	local lan_ip gateway bridge_wan hostname lan_proto wan_pppoe_user wan_pppoe_pass \
		  ssid_24g ssid_5g wifi_pass mesh_id mesh_pass init old_init old_hostname \
		  network_changed=0 wireless_changed=0

	config_load mesh_node
	config_get lan_ip        main  lan_ip         ''
	config_get gateway       main  gateway        ''
	config_get bridge_wan    main  bridge_wan     none
	config_get hostname      main  hostname       ''
	config_get lan_proto     main  lan_proto      ''
	config_get user          main  wan_pppoe_user ''
	config_get pass          main  wan_pppoe_pass ''

	config_get ssid_24g      main  ssid_24g       ''
	config_get ssid_5g       main  ssid_5g        ''
	config_get wifi_pass     main  wifi_pass      ''
	config_get mesh_id       main  mesh_id        HomeMesh
	config_get mesh_pass     main  mesh_pass      ''

	config_get init          main  init           ''
	config_get old_init      main  old_init       ''
	config_get old_hostname  main  old_hostname   ''

	[ "$hostname" != "$old_hostname" ] && {
		uci -q set system.@system[0].hostname="$hostname"
		uci -q set mesh_node.main.old_hostname="$hostname"
	}

	do_services
	do_network  && network_changed=1
	do_wireless && wireless_changed=1

	uci -q commit network
	uci -q commit wireless
	uci -q commit system
	uci -q commit dhcp
	uci -q commit mesh_node
	[ "$wireless_changed" = 1 ] && { wifi reload; sleep 3; }
	[ "$network_changed"  = 1 ] && /etc/init.d/network restart
}

stop() { :; }
