# 官方完整配置示例: https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml

Anchor_PR: &Anchor_PR {type: http, interval: 86400, proxy: DIRECT, health-check: {enable: true, url: 'https://www.g.cn/generate_204', interval: 300}, filter: "^(?!.*(到期|过期|剩余|网址|官网|邮箱|订阅|套餐|流量|说明|重置|域名)).*$"}
# ================= 机场订阅 =================
proxy-providers:
#  机场名: {<<: *Anchor_PR, url: '订阅链接', override: {additional-prefix: '[机场名] '}}

mode: "rule"
ipv6: false
port: 7893
socks-port: 1080
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
allow-lan: true
bind-address: "*"
unified-delay: true
tcp-concurrent: true
keep-alive-idle: 600
keep-alive-interval: 15
log-level: "warning"
find-process-mode: "off"
secret: "709777"
external-controller: '[::]:9090'
external-ui: ui
external-ui-name: Zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip

dns:
  enable: true
  ipv6: false
  use-hosts: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter: ["rule-set:private,Fifilter,China"]
  nameserver: ['https://dns.google/dns-query', 'https://cloudflare-dns.com/dns-query']
  direct-nameserver: ['https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
  proxy-server-nameserver: ['https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
  default-nameserver: [114.114.114.114, 8.8.8.8, 'tls://1.12.12.12:853', 'tls://223.5.5.5:853']
  nameserver-policy:
    'rule-set:reject': "rcode://success"
    'rule-set:Proxy,gfw': ['https://dns.google/dns-query', 'https://cloudflare-dns.com/dns-query']
    'rule-set:apple,China,private': ['https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']

hosts:
  'services.googleapis.cn': ['services.googleapis.com']

sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  sniff:
    TLS: {ports: [443, 8443]}
    QUIC: {ports: [443, 8443]}
    HTTP: {ports: [80, 8080-8880], override-destination: true}
  force-domain: ["+.netflix.com", "+.nflxvideo.net", "+.amazonaws.com", "+.media.dssott.com"]
  skip-domain: [Mijia Cloud, dlg.io.mi.com, "+.oray.com", "+.sunlogin.net", "+.push.apple.com"]

tun:
  enable: true
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  mtu: 1380
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

ntp:
  enable: true
  port: 123
  interval: 30
  write-to-system: false
  server: time.apple.com

profile:
  store-fake-ip: true
  store-selected: true

geodata-mode: false
geodata-loader: standard
geox-url:
  asn: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat

rules:
  - AND,((RULE-SET,Proxy),(DST-PORT,443),(NETWORK,UDP)),REJECT
  - RULE-SET,reject,REJECT
  - RULE-SET,private,🎯国内
  - RULE-SET,cdn_cn,🎯国内
  - RULE-SET,cpt,🎯国内
  - RULE-SET,pt,🎯国内
  - RULE-SET,download,🎯国内
  - RULE-SET,apple,🎯国内
  - RULE-SET,China,🎯国内
  - RULE-SET,claude,🚀AI
  - RULE-SET,ai,🚀AI
  # - RULE-SET,bybit,自动选择
  - RULE-SET,github,自动选择
  - RULE-SET,youtube,自动选择
  - RULE-SET,tiktok,自动选择
  - RULE-SET,netflix,自动选择
  # - RULE-SET,disney,自动选择
  - RULE-SET,telegram,自动选择
  # - RULE-SET,paypal,自动选择
  - RULE-SET,gfw,自动选择
  - RULE-SET,Proxy,自动选择
  - RULE-SET,ProxyIP,自动选择,no-resolve
  - RULE-SET,ChinaIP,🎯国内,no-resolve
  - MATCH,自动选择

proxies:
  - {name: 🎯国内, type: direct, udp: true, proxies: [DIRECT]}

A: &select   {include-all: true, url: "https://www.gstatic.com/generate_204", type: select}
B: &fallback {include-all: true, interval: 300, lazy: true, timeout: 2000, url: "https://www.gstatic.com/generate_204", type: fallback, max-failed-times: 3}
C: &balance  {include-all: true, interval: 300, lazy: true, timeout: 2000, url: "https://www.gstatic.com/generate_204", type: load-balance, strategy: consistent-hashing}
D: &urltest  {include-all: true, url: "https://www.gstatic.com/generate_204", type: url-test}

proxy-groups:
  # - {name: 故障转移, <<: *fallback, filter: "(?i)^(?!.*(国内)).*$", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/Rocket.png}
  - {name: 自动选择, <<: *urltest, filter: "(?i)^(?!.*(国内)).*$", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/Rocket.png}
  - {name: 🚀AI,    <<: *urltest, filter: "(?i)(台|日|美|新|韩)", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/Claude.png}
  - {name: 香港自动, <<: *urltest, filter: "(?i)(香港|HK)", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/HK.png}
  - {name: 日本自动, <<: *urltest, filter: "(?i)(日本|jp)", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/JP.png}
  - {name: 台湾自动, <<: *urltest, filter: "(?i)(台湾|tw)", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/TW.png}
  - {name: 美国自动, <<: *urltest, filter: "(?i)(美国|us)", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/US.png}
  - {name: 狮城自动, <<: *urltest, filter: "(?i)(新加|sg)", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/SG.png}
  - {name: 韩国自动, <<: *urltest, filter: "(?i)(韩国|🇰🇷)", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/KR.png}
  - {name: 其他,     <<: *urltest, filter: "(?i)^(?!.*(港|HK|台|日|美|新|国内|韩)).*$", icon: https://testingcf.jsdelivr.net/gh/Seven1echo/Yaml@main/icons/OT.png}

Im: &Im {type: http, behavior: ipcidr,    format: mrs,  interval: 86400}
Dm: &Dm {type: http, behavior: domain,    format: mrs,  interval: 86400}
Dy: &Dy {type: http, behavior: domain,    format: yaml, interval: 86400}
Ct: &Ct {type: http, behavior: classical, format: text, interval: 86400}
Cy: &Cy {type: http, behavior: classical, format: yaml, interval: 3600, proxy: DIRECT}

rule-providers:
  gfw:      {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/gfw.mrs}
  apple:    {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/apple.mrs}
  cpt:      {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-public-tracker.mrs}
  # bybit:    {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/bybit.mrs}
  # disney:   {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/disney.mrs}
  # paypal:   {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/paypal.mrs}
  tiktok:   {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/tiktok.mrs}
  github:   {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/github.mrs}
  private:  {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/private.mrs}
  youtube:  {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/youtube.mrs}
  netflix:  {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/netflix.mrs}
  telegram: {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/telegram.mrs}
  claude:   {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/anthropic.mrs}
  pt:       {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-pt.mrs}
  ai:       {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-ai-!cn.mrs}
  cdn_cn:   {<<: *Dm, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/category-cdn-cn.mrs}
  reject:   {<<: *Dm, url: https://github.com/wwqgtxx/clash-rules/raw/release/reject.mrs}
  Proxy:    {<<: *Dm, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Proxy.mrs}
  China:    {<<: *Dm, url: https://github.com/666OS/rules/raw/release/mihomo/domain/China.mrs}
  download: {<<: *Dm, url: https://github.com/666OS/rules/raw/release/mihomo/domain/Download.mrs}
  ProxyIP:  {<<: *Im, url: https://github.com/666OS/rules/raw/release/mihomo/ip/Proxy.mrs}
  ChinaIP:  {<<: *Im, url: https://github.com/666OS/rules/raw/release/mihomo/ip/China.mrs}
  Fifilter: {<<: *Dy, url: https://github.com/DustinWin/ShellCrash/raw/dev/public/fake_ip_filter.list}
