#!/bin/sh

touch /etc/config/wizard
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@wizard[-1]
	add ucitrack wizard
	set ucitrack.@wizard[-1].init=wizard
	commit ucitrack
	set wizard.default=wizard
	commit wizard
EOF

chmod +x /etc/init.d/wizard
chmod +x /etc/hotplug.d/button/99-wizard-restore

rm -f /tmp/luci-*
exit 0
