include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for mesh11sd
LUCI_DEPENDS:=+mesh11sd

PKG_NAME:=luci-app-mesh11sd
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
