#!/bin/sh
chmod +x /etc/init.d/watchdog \
		 /usr/libexec/watchdog-call \
		 /usr/share/watchdog/watchdog
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@watchdog[-1]
	add ucitrack watchdog
	set ucitrack.@watchdog[-1].init=watchdog
	commit ucitrack
EOF
rm -f /tmp/luci-indexcache
exit 0
