#!/bin/sh /etc/rc.common
#
# Copyright (C) 2023 sirpdboy herboy2008@gmail.com
#

START=99
USE_PROCD=1

CR=/etc/crontabs/root

start_service() {
	stop_service
	uci show eqosplus | grep "device.*enable='1'" || return 0
	if [ x$(uci -q get turboacc.config.sw_flow) = 'x1' -o x$(uci -q get turboacc.config.sfe_flow) = 'x1' ]; then
		uci -q set turboacc.config.sw_flow='0'
		uci -q set turboacc.config.hw_flow='0'
		uci -q set turboacc.config.sfe_flow='0'
		uci commit turboacc
		/etc/init.d/turboacc restart
	fi
	/usr/bin/eqosplus start
	procd_open_instance
	procd_set_param command /usr/bin/eqosplusctrl
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
	grep -q 'eqosplus start' $CR || \
		(crontab -l; echo "0 1 * * * /etc/init.d/eqosplus start") | uniq | crontab -
}

service_triggers() {
	procd_add_reload_trigger 'eqosplus'
}

stop_service(){
	kill -9 $(busybox ps -w | grep 'eqosplusctrl' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
	grep -q 'eqosplus' $CR && \
		sed -i '/eqosplus/d' $CR
	/usr/bin/eqosplus stop
}

reload_service() {
	restart
}
