#!/bin/sh
touch /etc/config/deluge
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@deluge[-1]
	add ucitrack deluge
	set ucitrack.@deluge[-1].init=deluge
	commit ucitrack

	set deluge.main=deluge
	commit deluge
EOF

rm -rf /tmp/luci-*
exit 0
