#!/bin/sh
chmod +x /etc/init.d/miaplus
echo "config basic 'config'" > /etc/config/miaplus
[ ! -f "/usr/share/ucitrack/luci-app-miaplus.json" ] && {
	cat > /usr/share/ucitrack/luci-app-miaplus.json << EOF
	{
	    "config": "miaplus",
	    "init": "miaplus"
	}
	EOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@miaplus[-1]
	add ucitrack miaplus
	set ucitrack.@miaplus[-1].init=miaplus
	commit ucitrack
	delete firewall.miaplus
	set firewall.miaplus=include
	set firewall.miaplus.type=script
	set firewall.miaplus.path=/etc/miaplus.include
	set firewall.miaplus.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
