#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

get_config() {
    local id token index name enabled
    config_get      id      $1 custom_id ''
    config_get      token   $1 token     ''
    config_get      index   $1 index     0
    config_get      name    $1 name      ''
    config_get_bool enabled $1 enabled   0

    [ "$enabled" != 1 ] && return 1
    [ -z "$token" ] && { logger -t ddnsto -p warn "token not set"; return 1; }

    procd_open_instance
    procd_set_param command /usr/sbin/ddnstod -u "$token" ${id:+-M "$id"} ${index:+-x $index} ${name:+-m "$name"} -daemon
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

ddnsto_prepare() {
    pidof ddnstod >/dev/null && killall ddnstod 2>/dev/null
    pidof ddwebdav >/dev/null && killall ddwebdav 2>/dev/null
}

stop_service() {
    ddnsto_prepare
}

start_service() {
    ddnsto_prepare
    config_load ddnsto
    config_foreach get_config ddnsto
}

service_triggers() {
    procd_add_reload_trigger ddnsto
}
