#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

get_config() {
    config_get token $1 token
    config_get index $1 index
    config_get threads $1 threads
    config_get log_level $1 log_level
    config_get_bool logger $1 logger
    config_get_bool enabled $1 enabled 1
    config_get_bool feat_enabled $1 feat_enabled 1

    [ "$enabled" != 1 ] && return 1
    [ -z "$token" ] && { logger -t ddnsto -p warn "token not set"; return 1; }
    [ "$threads" = 0 ] && threads="$(grep -c 'processor' /proc/cpuinfo)"

    procd_open_instance
    procd_set_param command /usr/sbin/ddnstod -u "$token" -c "$threads" "${index:+-x $index}" "${log_level:+-l $log_level}" -F
    [ "$logger" = 1 ] && procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

ddnsto_prepare() {
    pidof ddnstod >/dev/null && killall ddnstod 2>/dev/null
    pidof ddwebdav >/dev/null && killall ddwebdav 2>/dev/null
}

stop_service() {
    ddnsto_prepare
}

start_service() {
    ddnsto_prepare
    config_load ddnsto
    config_foreach get_config ddnsto
}

service_triggers() {
    procd_add_reload_trigger ddnsto
}
