#!/bin/sh

touch /etc/config/qbittorrent
[ -x /etc/init.d/qbittorrent ] || chmod +x /etc/init.d/qbittorrent
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qbittorrent[-1]
	add ucitrack qbittorrent
	set ucitrack.@qbittorrent[-1].init=qbittorrent
	commit ucitrack

	set qbittorrent.main=qbittorrent
	commit qbittorrent
EOF

rm -f /tmp/luci-indexcache
exit 0
