#!/bin/sh

touch /etc/config/qbittorrent
[ -s /etc/config/qbittorrent ] || \
	echo "config qbittorrent 'main'" > /etc/config/qbittorrent
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qbittorrent[-1]
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
