#!/bin/sh /etc/rc.common

START=99

run_bridge() {
	config_get enabled $1 enabled
	config_get gateway $1 gateway
	config_get ipaddr $1 ipaddr
	config_get netmask $1 netmask
	config_get network $1 network
	config_get ignore $1 ignore
	config_get masq $1 masq
	config_get firewall $1 firewall
	config_get fullcone $1 fullcone
	config_get syn_flood $1 syn_flood

	if [ "$enabled" -eq "1" ]; then
		#模拟输入
		if [ "$network" = "0" ] || [ "$network" = "" ]; then
			eth=$(ls /sys/class/net | grep "eth" | tr '\n' ' ' | sed 's/[ ]*$//g')
		else
			eth=$(ETH $network | tr '\n' ' ' | sed 's/[ ]*$//g')
		fi

		#写入network网络接口
		uci set network.lan.ipaddr=$ipaddr
		uci set network.lan.netmask=$netmask
		uci set network.lan.gateway=$gateway
		uci set network.lan.dns=$gateway
		uci set network.lan.ifname="$eth"
		uci commit network

		#写入dhcp
		if [ "$ignore" -eq "1" ]; then
			uci set dhcp.lan.ignore=$ignore
			uci -q delete dhcp.lan.start
			uci -q delete dhcp.lan.limit
			uci -q delete dhcp.lan.leasetime
			uci commit dhcp
		else
			uci set dhcp.lan.ignore=0
			uci set dhcp.lan.start=100
			uci set dhcp.lan.limit=150
			uci set dhcp.lan.leasetime=12h
			uci commit dhcp
		fi

		#写入firewall防火墙
		[ -z "$(grep eth0 /etc/firewall.user)" ] && echo 'iptables -t nat -I POSTROUTING -o eth0 -j MASQUERADE' >>/etc/firewall.user
		[ "$masq" ] && uci set firewall.@zone[0].masq='1' || uci set firewall.@zone[0].masq='0'
		[ "$fullcone" ] && uci set firewall.@defaults[0].fullcone='0' || uci set firewall.@defaults[0].fullcone='1'
		[ "$syn_flood" ] && uci set firewall.@defaults[0].syn_flood='0' || uci set firewall.@defaults[0].syn_flood='1'
		uci set firewall.@zone[0].name=bridge
		uci commit firewall

		#重启网络与防火墙
		/etc/init.d/network restart 2>/dev/null &
		/etc/init.d/firewall restart 2>/dev/null &
	else
		#恢复firewall
		uci set firewall.@zone[0].masq='0'
		uci set firewall.@zone[0].name=lan
		uci set firewall.@defaults[0].fullcone='1'
		uci set firewall.@defaults[0].syn_flood='1'
		sed -i '/eth0/d' /etc/firewall.user

		#恢复dhcp
		uci set dhcp.lan.ignore=0
		uci set dhcp.lan.start=100
		uci set dhcp.lan.limit=150
		uci set dhcp.lan.leasetime=12h
		uci commit dhcp

		#恢复network
		uci delete network.lan.gateway
		uci delete network.lan.dns
		uci set network.lan.ifname=eth0
		uci commit network

		#重启网络与防火墙
		/etc/init.d/network restart 2>/dev/null &
		/etc/init.d/firewall restart 2>/dev/null &
	fi
}

ETH() {
	eth=0
	while [ $eth -le $(expr "$1" - 1) ]; do
		eth=$(expr $eth + 1)
		a=$(expr $eth - 1)
		echo "eth$a"
	done
}

start() {
	config_load bridge
	config_foreach run_bridge bridge
}
