#!/bin/sh
mkdir -p /etc/taskplan
echo "# Sh script rules" > /etc/taskplan/taskplancustomscript
echo "# Sh script2 rules" > /etc/taskplan/taskplancustomscript2
chmod +x /etc/init.d/taskplan \
		 /usr/bin/taskplanhandler \
		 /etc/taskplan/taskplancustomscript \
		 /etc/taskplan/taskplancustomscript2
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@taskplan[-1]
	add ucitrack taskplan
	set ucitrack.@taskplan[-1].init="taskplan"
	commit ucitrack
EOF
rm -rf /tmp/luci-*
exit 0
